openapi: 3.0.0

info:
  title: Money Service API
  version: 1.0.0
  description: Simple API to create, get and operate on monetary amounts
servers:
  - url: http://localhost:8080

paths:
  /downloads:
    post:
      summary: Download files
      description: Скачивание документов по переданному набору ссылок.
      requestBody:
        required: true # тело обязательно
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DownloadsRequest"
            example:
              $ref: "#/components/examples/InitTaskReq"
      responses:
        "201":
          description: Document created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DownloadsResponse"
              example:
                $ref: "#/components/examples/InitTaskResp"
        "400":
          $ref: '#/components/responses/BadRequest400'
        "500":
          $ref: '#/components/responses/InternalServerError500'
  /downloads/{id}:
    get:
      summary: Просмотр статусов
      description:  Просмотр заявки на скачивание набора файлов.
      parameters:
        - $ref: "#/components/parameters/IdTaskPar"
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DownloadsIdResponse"
        "400":
          $ref: '#/components/responses/BadRequest400'
        "404":
          $ref: '#/components/responses/NotFound404'
        "500":
          $ref: '#/components/responses/InternalServerError500'

  /downloads/{id}/files/{file_id}:
    get:
      summary: Скачивание файла
      description: Скачивание файла по ID таска и ID файла
      parameters:
        - $ref: "#/components/parameters/IdTaskPar"
        - $ref: "#/components/parameters/IdFilePar"
      responses:
        "200":
          description: success
          content:
            application/octet-stream:
              schema:
                $ref: "#/components/schemas/DownloadsIdResponse"
        "400":
          $ref: '#/components/responses/BadRequest400'
        "404":
          $ref: '#/components/responses/NotFound404'
        "500":
          $ref: '#/components/responses/InternalServerError500'


components:
  schemas:
    UrlString:
      type: string
      format: uri #автопроверка формала URL
      description: URL для скачивания файла

    Url:
      type: object
      required:
        - url
      properties:
        url:
          $ref: "#/components/schemas/UrlString"

    IdTask:
      type: integer
      description: ID заявки, по которому можно опрашивать статус скачивания файлов

    TaskStatus:
      type: string
      description: Статус заявки
      enum: [ PROCESS, DONE ]

    UrlFile:
      required: [ url, file_id ]
      properties:
        url:
          $ref: "#/components/schemas/UrlString"
        file_id:
          type: integer

    UrlErr:
      required: [ url, error ]
      properties:
        url:
          $ref: "#/components/schemas/UrlString"
        error:
          required: [ code ]
          type: object
          properties:
            code:
              type: string

    DownloadsRequest:
      type: object
      required: [files, timeout]
      properties:
        files:
          type: array
          description: массив URL для скачивания
          items:
            $ref: "#/components/schemas/Url"
        timeout:
          type: string
          pattern: "^[0-9]+s$"
          description: таймаут в секундах

    DownloadsResponse:
      type: object
      required: [id, status]
      properties:
        id:
          $ref: "#/components/schemas/IdTask"
        status:
          $ref: "#/components/schemas/TaskStatus"

    DownloadsIdResponse:
      type: object
      required: [id, status, files]
      properties:
        id:
          $ref: "#/components/schemas/IdTask"
        status:
          $ref: "#/components/schemas/TaskStatus"
        files:
          type: array
          items:
            type: object
            oneOf:
              - $ref: "#/components/schemas/UrlFile"
              - $ref: "#/components/schemas/UrlErr"

    ErrorResponse:
      type: object
      required: [code, message]
      properties:
        code:
          $ref: "#/components/schemas/ErrorCode"
        message:
          type: string

    ErrorCode:
      type: string
      description: Код ошибки для файла
      enum: [ TIMEOUT, NOT_FOUND, FORBIDDEN, BAD_REQUEST, INTERNAL_SERVER_ERROR]

  examples:
    InitTaskReq:
      summary: Start task example
      value:
        files:
          - url: "https://google.com"
          - url: "https://somehost.com/test.pdf"
        timeout: "60s"
    InitTaskResp:
      summary: Start task example
      value:
        id: "0"
        status: "60s"
    CompletedTask:
      summary: Completed task example
      value:
        id: 1
        status: "completed"

  parameters:
    IdTaskPar:
      name: id
      in: path
      description: Уникальный идентификатор заявки на скачивание
      required: true
      schema:
        type: integer
    IdFilePar:
      name: file_id
      in: path
      description: Уникальный идентификатор заявки на скачивание
      required: true
      schema:
        type: integer


  responses:
    BadRequest400:
      description: Некорректное тело запроса
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    NotFound404:
      description: Данные не найдены
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    InternalServerError500:
      description: Внутренняя ошибка сервиса
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
